### ISSUE TITLE
[Bug] Error resetting/recovering password

### ISSUE THREAD

**Issue by jessief25** [ScottyLabs/tartanhacks_dashboard_v2#92]
### Expected Behavior

Sends an email to user to reset password

### Steps to Reproduce

the account was made during winter break (may have been made with the production instead of the dev link) --> investigate

![IMG_6094 - Houer Deng](https://user-images.githubusercontent.com/106046044/213886585-9bb41b18-fa76-46be-8afc-d55830d52645.jpeg)

### Device Information

Desktop/Mobile: Desktop
OS: macOS Monterey 12.3.1
Browser Version: Safari 15.4

**Comment by hdavidethan** [comment]
Not a bug
